[kaltemplate] Get kaltemplate to a usable level

diff --git a/Code/Projects/kaltemplate/kaltemplate b/Code/Projects/kaltemplate/kaltemplate
--- a/Code/Projects/kaltemplate/kaltemplate
+++ b/Code/Projects/kaltemplate/kaltemplate
@@ -6,10 +6,9 @@ SCOPE="global"
 
 HIGHLIGHT_TABWIDTH=2
 HIGHLIGHT_STYLE='pablo'
+HIGHLIGHT_FORMAT='ansi'
 if [ "$( tput colors )" -ge 256 ]; then
-    HIGHLIGHT_FORMAT='xterm256'
-else
-    HIGHLIGHT_FORMAT='ansi'
+    Highlight_FORMAT='xterm256'
 fi
 
 echoCentered(){
@@ -36,32 +35,111 @@ prepareConfig(){
 mkTemplate(){
     local name="$1"
     local path="$2"
+    #TODO: Have multiple ways to generate scopes
     mkdir -p "$(configdir)/templates/$name/$(uname -n)"
     mkdir -p "$(configdir)/templates/$name/disabled"
+    mkdir -p "$(configdir)/templates/$name/global"
     echo -e "$path" > "$(configdir)/templates/$name/.template"
 }
 
 highlightFile(){
     local file="$1"
     highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" \
-                      --out-format="${highlight_format}" \
+                      --out-format="${HIGHLIGHT_FORMAT}" \
                       --style="${HIGHLIGHT_STYLE}" --force -- "$file"
+}
+
+listTemplates(){
+    tree "$(configdir)/templates" | sed -E "s|$(configdir)/templates|Templates|;/^[0-9]+ directories/d;/^$/d;s/(.*)\.unit/\1/g"
+}
+
+viewCompiled(){
+    template="$1"
+    highlightFile "$(configdir)/templates/$template/.kalc" | less
+}
+
+collectScopes(){
+    echo "Looking for available scopes..." 1>&2
+    n=0
+    for i in "$(configdir)/scopes/"*
+    do
+        scope="$($i)"
+        echo "  Found scope '$scope' of type '$(echo $i | rev | cut -d/ -f1 | rev)'" 1>&2
+        echo "$scope"
+        n=$(( ++n ))
+    done
+    echo "Found $n scopes." 1>&2
+}
+
+collectUnits(){
+    template="$1"
+    shift
+    for i in $@
+    do
+        find "$template/$i" -type f -regex ".*.unit"
+    done
+}
+
+collectTemplates(){
+    scopes=( $(collectScopes) )
+
+    echo "Collecting templates..."
+    templates=($(find $(configdir)/templates -mindepth 1 -maxdepth 1 -type d))
+    templateCount=${#templates[@]}
+    m=0
+    for template in "${templates[@]}"
+    do
+        m=$(( ++m ))
+        echo "Collecting '$(echo "$template" | rev | cut -d/ -f1 | rev)' [$m/$templateCount]"
+        echo "  Collecting units..."
+        units=( $(collectUnits "$template" "${scopes[@]}") )
+        unitCount=${#units[@]}
+        echo -n > "$template/.kalc"
+        n=0
+        for unit in "${units[@]}"
+        do
+            n=$(( ++n ))
+            echo "    Collecting '$(echo "$unit" | sed "s|$(configdir)/templates/||g;s/\.unit//g;s|/|.|g")' [$n/$unitCount]"
+            #format "$unit" >> "$template/.kalc"
+            cat "$unit" >> "$template/.kalc"
+            echo >> "$template/.kalc"
+        done
+    done
 }
 
 collectTemplate(){
     local template="$1"
+    local suppressComments="$2"
 
-    files=( $(find "$(configdir)/templates/$template" -maxdepth 1 -type f -regex ".*.unit"))
+    scopes=( $(collectScopes) )
+    files=( $(collectUnits "$(configdir)/templates/$template" "${scopes[@]}") )
 
-    files+=( $(find "$(configdir)/templates/$template/$(uname -n)" -maxdepth 1 -type f -regex ".*.unit") )
+    [ -z "$suppressComments" ] && {
 
-    cat "${files[@]}"
+        echo "# Generated by kaltemplate '$KALTEMPLATE_VERSION' on $(date)"
+        echo "# Expansion of template '$template'"
+        echo
+
+        for file in "${files[@]}"
+        do
+            echo "########### From '$file' ##########"
+            cat "$file"
+            echo -e "\n###################################\n"
+        done
+
+    } || {
+        for file in "${files[@]}"
+        do
+            cat "$file"
+            echo -e "\n"
+        done
+    }
 }
 
 viewTemplate(){
     local template="$1"
 
-    [ -z "$PAGER" ] && PAGER=less
+     [ -z "$PAGER" ] && PAGER=less
 
     collectTemplate "$template" > tmp
 
@@ -72,6 +150,7 @@ viewTemplate(){
 
 dereferenceUnit(){
     local unit="$1"
+    local createFile="$2"
 
     local template=$(echo "$unit" | cut -d. -f1)
     local scope=$(echo "$unit" | cut -d. -f2)
@@ -82,37 +161,30 @@ dereferenceUnit(){
         scope="global"
     }
 
-
     [ -d "$(configdir)/templates/$template" ] || {
         echo -e "Cannot dereference unit '$unit'.\nTemplate '$template' doesn't exist."
         return 1
     }
 
-    if [ "$scope" != "global" ]
-    then
-        [ -d "$(configdir)/templates/$template/$scope" ] || {
-            echo -e "Cannot dereference unit '$unit'.\nTemplate '$template' doesn't have scope '$scope'."
-            return 2
-        }
+    [ -d "$(configdir)/templates/$template/$scope" ] || {
+        echo -e "Cannot dereference unit '$unit'.\nTemplate '$template' doesn't have scope '$scope'."
+        return 2
+    }
 
-        [ -f "$(configdir)/templates/$template/$scope/$unitFile.unit" ] ||  {
-            echo -e "Cannot dereference unit '$unit'.\nTemplate '$template' doesn't have unitfile '$unitFile' in scope '$scope'."
+    [ -f "$(configdir)/templates/$template/$scope/$unitFile.unit" ] ||  {
+
+        [ -z "$createFile" ] && {
+            echo -e "Cannot dereference unit '$unit'.\n\
+Template '$template' doesn't have unitfile '$unitFile' in scope '$scope'."
             return 3
+        } || {
+            touch "$(configdir)/templates/$template/$scope/$unitFile.unit"
         }
+    }
 
-    else
-
-        [ -f "$(configdir)/templates/$template/$unitFile.unit" ] ||  {
-            echo -e "Cannot dereference unit '$unit'.\nTemplate '$template' doesn't have unitfile '$unitFile' in global scope."
-            return 3
-        }
-
-    fi
-
-
-    echo "$(configdir)/templates/$(echo "$unit" | sed 's|\.|/|g').unit"
+    echo "$(configdir)/templates/$template/$scope/$unitFile.unit"
 }
-w
+
 viewUnit(){
     local unit="$1"
 
@@ -124,6 +196,17 @@ viewUnit(){
     else
         echo "$unitPath"
         echo "Failed to view unit '$unit'"
+    fi
+}
+
+editUnit(){
+    local unit="$1"
+    if unitPath="$(dereferenceUnit "$1" true)"
+    then
+        $EDITOR "$unitPath"
+    else
+        echo "$unitPath"
+        echo "Failed to edit unit '$unit'"
     fi
 }
 
@@ -198,7 +281,7 @@ createTemplate(){
                 ;;
         esac
     done
-
+    tput rmcup
 }
 
 while [ -n "$1" ]
@@ -208,14 +291,32 @@ do
             createTemplate
             shift
             ;;
+        edit)
+            shift
+            editUnit "$1"
+            shift
+            ;;
         viewUnit)
             shift
             viewUnit "$1"
             shift
             ;;
+        list)
+            listTemplates
+            shift
+            ;;
+        collect)
+            collectTemplates
+            shift
+            ;;
         viewTemplate)
             shift
             viewTemplate "$1"
+            shift
+            ;;
+        view)
+            shift
+            viewCompiled "$1"
             shift
             ;;
         *)
